services:
  - type: web
    name: carrent-comores
    env: python3.10
    buildCommand: pip install -r requirements.txt
    startCommand: flask db upgrade && gunicorn app:app
    envVars:
      - key: SECRET_KEY
        value: 265afb09533257ad9db63f7eadc3f798
      - key: FLASK_DEBUG
        value: "False"
      - key: DB_USERNAME
        value: carrent_user
      - key: DB_PASSWORD
        value: WfBNpgfvZEcSoUTruafyT8wE9MFEYyhs
      - key: DB_HOST
        value: dpg-cv21qj0gph6c73bbq1lg-a.oregon-postgres.render.com
      - key: DB_NAME
        value: carrent_ak7c
      - key: DATABASE_URL
        value: postgresql://carrent_user:WfBNpgfvZEcSoUTruafyT8wE9MFEYyhs@dpg-cv21qj0gph6c73bbq1lg-a.oregon-postgres.render.com/carrent_ak7c?sslmode=require

databases:
  - name: carrent-db
    databaseName: carrent_ak7c
    user: carrent_user
    plan: free
